// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("ErrorLog")]
[Index("CreatedAt", Name = "IX_ErrorLog_CreatedAt")]
[Index("MethodName", Name = "IX_ErrorLog_MethodName")]
[Index("ServiceName", Name = "IX_ErrorLog_ServiceName")]
public partial class ErrorLog
{
    /// <summary>
    /// 自動インクリメントのプライマリキー
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// エラーが発生したサービス名やモジュール名
    /// </summary>
    public string ServiceName { get; set; }

    /// <summary>
    /// エラーが発生したメソッド名
    /// </summary>
    public string MethodName { get; set; }

    /// <summary>
    /// エラーメッセージ
    /// </summary>
    [Required]
    public string ErrorMessage { get; set; }

    /// <summary>
    /// エラーのスタックトレース
    /// </summary>
    [Required]
    public string StackTrace { get; set; }

    /// <summary>
    /// 任意の補足情報（リクエストデータなど）
    /// </summary>
    public string AdditionalInfo { get; set; }

    /// <summary>
    /// レコードの作成日時（記録時点）
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }
}