// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("ErrorLog")]
[Index("CreatedAt", Name = "IX_ErrorLog_CreatedAt")]
public partial class ErrorLog
{
    /// <summary>
    /// 一意の識別子（自動採番）
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// エラー内容を記録するメッセージ
    /// </summary>
    [Required]
    public string ErrorMessage { get; set; }

    /// <summary>
    /// エラーに関連するスタックトレース
    /// </summary>
    public string StackTrace { get; set; }

    /// <summary>
    /// エラーの発生元（例: アプリケーション名、サービス名）
    /// </summary>
    [StringLength(255)]
    public string ErrorSource { get; set; }

    /// <summary>
    /// エラーが記録された日時
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// エラーに関する任意の追加情報
    /// </summary>
    public string AdditionalInfo { get; set; }
}