// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("OrderDetail")]
[Index("OrderDetailCode", Name = "UK_OrderDetail_OrderDetailCode", IsUnique = true)]
public partial class OrderDetail
{
    /// <summary>
    /// 注文明細の一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 注文の一意の注文コード（各モールの注文ID）
    /// </summary>
    [Required]
    [StringLength(35)]
    [Unicode(false)]
    public string OrderCode { get; set; }

    /// <summary>
    /// 注文明細の一意コード
    /// </summary>
    [Required]
    [StringLength(39)]
    [Unicode(false)]
    public string OrderDetailCode { get; set; }

    /// <summary>
    /// SKUの一意コード
    /// </summary>
    [Required]
    [Column("SKUCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string Skucode { get; set; }

    /// <summary>
    /// 注文数量（3桁：999）
    /// </summary>
    [Column("OrderQTY")]
    public int OrderQty { get; set; }

    /// <summary>
    /// 消費税率
    /// </summary>
    [Column(TypeName = "decimal(5, 3)")]
    public decimal ConsumptionTaxRate { get; set; }

    /// <summary>
    /// オリジナル価格（税込）
    /// </summary>
    [Column(TypeName = "decimal(8, 2)")]
    public decimal OriginalPrice { get; set; }

    /// <summary>
    /// クーポン値引き（税込）
    /// </summary>
    [Column(TypeName = "decimal(7, 2)")]
    public decimal CouponDiscount { get; set; }

    /// <summary>
    /// 注文明細合計（税込）=オリジナル価格-クーポン値引き
    /// </summary>
    [Column(TypeName = "decimal(8, 2)")]
    public decimal OrderDetailTotal { get; set; }

    /// <summary>
    /// 月次仕入原価の一意コード（yyyymm_xxxxxxx：出荷年月 + &quot;_&quot; + SKUCode）
    /// </summary>
    [Column("CostID")]
    [StringLength(37)]
    [Unicode(false)]
    public string CostId { get; set; }

    /// <summary>
    /// レコード作成日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// レコード更新日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("OrderCode")]
    [InverseProperty("OrderDetails")]
    public virtual OrderHeader OrderCodeNavigation { get; set; }

    [InverseProperty("OrderDetailCodeNavigation")]
    public virtual ICollection<ShipmentDetail> ShipmentDetails { get; set; } = new List<ShipmentDetail>();

    [ForeignKey("Skucode")]
    [InverseProperty("OrderDetails")]
    public virtual ProductSku SkucodeNavigation { get; set; }
}