// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("OrderHeader")]
[Index("OrderCode", Name = "UK_OrderHeader_OrderCode", IsUnique = true)]
public partial class OrderHeader
{
    /// <summary>
    /// 注文の一意の識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 注文の一意コード（各モールの注文ID）
    /// </summary>
    [Required]
    [StringLength(35)]
    [Unicode(false)]
    public string OrderCode { get; set; }

    /// <summary>
    /// 注文日時（楽天は注文確定日時）
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    /// <summary>
    /// Shopマスタの一意のショップコード
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ShopCode { get; set; }

    /// <summary>
    /// レコード作成日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// レコード更新日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("OrderCodeNavigation")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("ShopCode")]
    [InverseProperty("OrderHeaders")]
    public virtual Shop ShopCodeNavigation { get; set; }
}