// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("ProductSKU")]
[Index("Skucode", Name = "UQ_ProductSKU_SKUCode", IsUnique = true)]
public partial class ProductSku
{
    /// <summary>
    /// 商品SKUマスタの一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 商品マスタの一意の商品コード
    /// </summary>
    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    /// <summary>
    /// SKUの一意コード
    /// </summary>
    [Required]
    [Column("SKUCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string Skucode { get; set; }

    /// <summary>
    /// 販売区分（Set：セット品販売、SKU：単品販売）
    /// </summary>
    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string SalesCategory { get; set; }

    /// <summary>
    /// SKUの正式な名称
    /// </summary>
    [Required]
    [Column("SKUName")]
    [StringLength(30)]
    public string Skuname { get; set; }

    /// <summary>
    /// SKUの略称。簡易表示用
    /// </summary>
    [Required]
    [Column("SKUAbbr")]
    [StringLength(15)]
    public string Skuabbr { get; set; }

    /// <summary>
    /// SKUの画像のURL
    /// </summary>
    [Column("ImageURL")]
    [StringLength(255)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    /// <summary>
    /// SKUの仕入れ先のURL
    /// </summary>
    [Column("SupplierURL")]
    [StringLength(255)]
    [Unicode(false)]
    public string SupplierUrl { get; set; }

    /// <summary>
    /// SKUごとの表示順序
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// SKUが有効かどうかを示すフラグ
    /// </summary>
    public bool IsActive { get; set; }

    [InverseProperty("SkucodeNavigation")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("ProductCode")]
    [InverseProperty("ProductSkus")]
    public virtual Product ProductCodeNavigation { get; set; }

    [InverseProperty("SetSkucodeNavigation")]
    public virtual ICollection<SetProductSku> SetProductSkuSetSkucodeNavigations { get; set; } = new List<SetProductSku>();

    [InverseProperty("SkucodeNavigation")]
    public virtual ICollection<SetProductSku> SetProductSkuSkucodeNavigations { get; set; } = new List<SetProductSku>();
}