// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("SetProductSKU")]
public partial class SetProductSku
{
    /// <summary>
    /// セット品構成マスタの一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// セット商品のコード（セット商品コードは商品SKUのSKUコードとN対１の関係）
    /// </summary>
    [Required]
    [Column("SetSKUCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string SetSkucode { get; set; }

    /// <summary>
    /// SKUコードは商品SKUのSKUコードとN対１の関係
    /// </summary>
    [Required]
    [Column("SKUCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string Skucode { get; set; }

    /// <summary>
    /// 構成SKUの数量
    /// </summary>
    [Column("ComponentQTY")]
    public int ComponentQty { get; set; }

    [ForeignKey("SetSkucode")]
    [InverseProperty("SetProductSkuSetSkucodeNavigations")]
    public virtual ProductSku SetSkucodeNavigation { get; set; }

    [ForeignKey("Skucode")]
    [InverseProperty("SetProductSkuSkucodeNavigations")]
    public virtual ProductSku SkucodeNavigation { get; set; }
}