// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("ShipmentDetail")]
[Index("ShipmentDetailCode", Name = "UK_ShipmentDetail_ShipmentDetailCode", IsUnique = true)]
public partial class ShipmentDetail
{
    /// <summary>
    /// 出荷明細の一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 出荷の一意の出荷コード
    /// </summary>
    [Required]
    [StringLength(14)]
    [Unicode(false)]
    public string ShipmentCode { get; set; }

    /// <summary>
    /// 出荷明細の一意コード（yymmdd-xxx-xxx-L99：出荷コード+L連番）
    /// </summary>
    [Required]
    [StringLength(18)]
    [Unicode(false)]
    public string ShipmentDetailCode { get; set; }

    /// <summary>
    /// 注文明細の一意のコード
    /// </summary>
    [Required]
    [StringLength(39)]
    [Unicode(false)]
    public string OrderDetailCode { get; set; }

    /// <summary>
    /// 出荷送料を明細ごとに按分
    /// </summary>
    [Column(TypeName = "decimal(7, 2)")]
    public decimal DeliveryDetailFee { get; set; }

    /// <summary>
    /// 梱包数量
    /// </summary>
    [Column("PackingQTY")]
    public int PackingQty { get; set; }

    /// <summary>
    /// 検品済みフラグ
    /// </summary>
    public bool InspectionFlag { get; set; }

    /// <summary>
    /// レコード作成日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// レコード更新日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("OrderDetailCode")]
    [InverseProperty("ShipmentDetails")]
    public virtual OrderDetail OrderDetailCodeNavigation { get; set; }

    [ForeignKey("ShipmentCode")]
    [InverseProperty("ShipmentDetails")]
    public virtual Shipment ShipmentCodeNavigation { get; set; }
}