// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

public partial class ShippingCondition
{
    /// <summary>
    /// 自動インクリメントのプライマリキー
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 配送条件グループID
    /// </summary>
    [Required]
    [Column("ShippingGroupID")]
    [StringLength(20)]
    [Unicode(false)]
    public string ShippingGroupId { get; set; }

    /// <summary>
    /// しきい値（注文数量がこの値以上で条件適用）
    /// </summary>
    public int MinThresholdQuantity { get; set; }

    /// <summary>
    /// 1梱包に詰められる最大数量
    /// </summary>
    public int MaxPackageCapacity { get; set; }

    /// <summary>
    /// 配送の一意コード（3桁：XXX）
    /// </summary>
    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string DeliveryCode { get; set; }

    [ForeignKey("DeliveryCode")]
    [InverseProperty("ShippingConditions")]
    public virtual Delivery DeliveryCodeNavigation { get; set; }

    [ForeignKey("ShippingGroupId")]
    [InverseProperty("ShippingConditions")]
    public virtual ShippingGroup ShippingGroup { get; set; }
}