// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Index("ShippingGroupId", Name = "UK_ShippingGroups_ShippingGroupID", IsUnique = true)]
public partial class ShippingGroup
{
    /// <summary>
    /// 自動インクリメントのプライマリキー
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 配送条件グループID
    /// </summary>
    [Required]
    [Column("ShippingGroupID")]
    [StringLength(20)]
    [Unicode(false)]
    public string ShippingGroupId { get; set; }

    /// <summary>
    /// 配送条件グループ名
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ShippingGroupName { get; set; }

    [InverseProperty("ShippingGroup")]
    public virtual ICollection<ShippingCondition> ShippingConditions { get; set; } = new List<ShippingCondition>();

    [InverseProperty("ShippingGroup")]
    public virtual ICollection<ShippingGroupMember> ShippingGroupMembers { get; set; } = new List<ShippingGroupMember>();

    [InverseProperty("ShippingGroup")]
    public virtual ICollection<ShopToShippingGroup> ShopToShippingGroups { get; set; } = new List<ShopToShippingGroup>();
}