// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

public partial class ShippingGroupMember
{
    /// <summary>
    /// 自動インクリメントのプライマリキー
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 配送条件グループID
    /// </summary>
    [Required]
    [Column("ShippingGroupID")]
    [StringLength(20)]
    [Unicode(false)]
    public string ShippingGroupId { get; set; }

    /// <summary>
    /// 構成商品メンバー識別（Product/SKU）
    /// </summary>
    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string MemberType { get; set; }

    /// <summary>
    /// ProductCodeまたはSKUCode
    /// </summary>
    [Required]
    [Column("MemberID")]
    [StringLength(30)]
    [Unicode(false)]
    public string MemberId { get; set; }

    [ForeignKey("ShippingGroupId")]
    [InverseProperty("ShippingGroupMembers")]
    public virtual ShippingGroup ShippingGroup { get; set; }
}