// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Index("ShopCode", Name = "UQ_ShopTokens_ShopCode", IsUnique = true)]
public partial class ShopToken
{
    /// <summary>
    /// 認証トークン管理の一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// Shopマスタの一意コード
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ShopCode { get; set; }

    /// <summary>
    /// 店舗ID（店舗URL）
    /// </summary>
    [Column("SellerID")]
    [StringLength(15)]
    [Unicode(false)]
    public string SellerId { get; set; }

    /// <summary>
    /// ヤフー専用（client , server）
    /// </summary>
    [StringLength(6)]
    [Unicode(false)]
    public string AppType { get; set; }

    /// <summary>
    /// ヤフー：クライアントID、楽天：LicenseKey
    /// </summary>
    [Required]
    [Column("ClientID")]
    [StringLength(255)]
    [Unicode(false)]
    public string ClientId { get; set; }

    /// <summary>
    /// ヤフー：シークレット、楽天：サービスシークレット
    /// </summary>
    [StringLength(255)]
    [Unicode(false)]
    public string Secret { get; set; }

    /// <summary>
    /// コールバックURL
    /// </summary>
    [Column("CallbackURI")]
    [StringLength(255)]
    [Unicode(false)]
    public string CallbackUri { get; set; }

    /// <summary>
    /// ヤフー専用（許可コード）
    /// </summary>
    [StringLength(15)]
    [Unicode(false)]
    public string AuthCode { get; set; }

    /// <summary>
    /// ヤフー専用（公開キー）
    /// </summary>
    [Column(TypeName = "text")]
    public string PublicKey { get; set; }

    /// <summary>
    /// ヤフー専用（公開キーバージョン）
    /// </summary>
    public int? PublicKeyVersion { get; set; }

    /// <summary>
    /// ヤフー専用（公開キー有効期限）
    /// </summary>
    [Column("PKExpiresAt", TypeName = "datetime")]
    public DateTime? PkexpiresAt { get; set; }

    /// <summary>
    /// ヤフー専用（アクセストークン）
    /// </summary>
    [StringLength(3072)]
    [Unicode(false)]
    public string AccessToken { get; set; }

    /// <summary>
    /// ヤフー専用（リフレッシュトークン）
    /// </summary>
    [StringLength(512)]
    [Unicode(false)]
    public string RefreshToken { get; set; }

    /// <summary>
    /// トークンの種類（Basic、Bearer）
    /// </summary>
    [StringLength(10)]
    [Unicode(false)]
    public string TokenType { get; set; }

    /// <summary>
    /// ヤフー専用（アクセストークン有効期限）
    /// </summary>
    [Column("ATExpiresAt", TypeName = "datetime")]
    public DateTime? AtexpiresAt { get; set; }

    /// <summary>
    /// ヤフー専用（リフレッシュトークン有効期限）
    /// </summary>
    [Column("RTExpiresAt", TypeName = "datetime")]
    public DateTime? RtexpiresAt { get; set; }

    /// <summary>
    /// レコード更新日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("ShopCode")]
    [InverseProperty("ShopToken")]
    public virtual Shop ShopCodeNavigation { get; set; }
}