// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("Shop")]
[Index("ShopCode", Name = "UK_Shop_ShopCode", IsUnique = true)]
public partial class Shop
{
    /// <summary>
    /// Shopマスタの一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// Yahoo、Rakuten、Amazon
    /// </summary>
    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string MallCode { get; set; }

    /// <summary>
    /// Shopマスタの一意コード
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ShopCode { get; set; }

    /// <summary>
    /// LARAL、Yours、ENZO
    /// </summary>
    [Required]
    [StringLength(15)]
    public string ShopName { get; set; }

    /// <summary>
    /// モールショップが有効かどうかを示すフラグ
    /// </summary>
    public bool IsActive { get; set; }

    [InverseProperty("ShopCodeNavigation")]
    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();

    [InverseProperty("ShopCodeNavigation")]
    public virtual ShopToken ShopToken { get; set; }

    [InverseProperty("ShopCodeNavigation")]
    public virtual ICollection<Skuconversion> Skuconversions { get; set; } = new List<Skuconversion>();
}