// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ssAppModels.EFModels;

[Table("SKUConversion")]
[Index("ShopCode", "ProductCode", "Skucode", "ShopProductCode", "ShopSkucode", Name = "UK_SKUConversion_ShopCode_ProductCode_SKUCode", IsUnique = true)]
public partial class Skuconversion
{
    /// <summary>
    /// SKU変換マスタの一意識別子
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// Shopマスタの一意のショップコード
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ShopCode { get; set; }

    /// <summary>
    /// 変換元商品コード（商品コード）
    /// </summary>
    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    /// <summary>
    /// 変換元SKUコード（商品SKUコード）
    /// </summary>
    [Required]
    [Column("SKUCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string Skucode { get; set; }

    /// <summary>
    /// 変換先商品コード（ショップ商品コード）
    /// </summary>
    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string ShopProductCode { get; set; }

    /// <summary>
    /// 変換先SKUコード（ショップSKUコード）
    /// </summary>
    [Required]
    [Column("ShopSKUCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string ShopSkucode { get; set; }

    [ForeignKey("ProductCode")]
    [InverseProperty("Skuconversions")]
    public virtual Product ProductCodeNavigation { get; set; }

    [ForeignKey("ShopCode")]
    [InverseProperty("Skuconversions")]
    public virtual Shop ShopCodeNavigation { get; set; }

    [ForeignKey("Skucode")]
    [InverseProperty("Skuconversions")]
    public virtual ProductSku SkucodeNavigation { get; set; }
}